AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an EC2 instance in a VPC.

Parameters:
  MyPublicIP:
    Type: String
    Description: Your public IP address 

Resources:
  # Create a VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

# Create the EC2 instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0fff1b9a61dec8a5f  


      KeyName: AWS-Keypair 
      Tags:
        - Key: Name
          Value: MyEC2Instance

